name: flutter_html_renderer
description: Simple HTML renderer for flutter. Converts HTML into Widgets
version: 0.1.2
author: Martin Hlavňa <mato.hlavna@gmail.com>
homepage: https://github.com/MartinHlavna/flutter_html_renderer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  html: ^0.14.0
  flutter_advanced_networkimage: ^0.5.0
  url_launcher: ^5.1.2
  youtube_player_flutter: ^4.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

